### ISSUE TITLE
 Error encountered resolving symbol values statically, DATE_PIPE_CONFIGURATION_TOKEN as ea error

### ISSUE THREAD

**Issue by von-dee** [Aaron-Sterling/ng-datefns-pipes#1]
![error](https://user-images.githubusercontent.com/22178823/36476771-b9ca7bea-16f6-11e8-89da-87ed5c6ddad2.PNG)

please i get this error when building release version of my app. Any help?. Thanks in andvance

**Comment by Aaron-Sterling** [comment]
Can you post a simple repo where this happens please?

**Comment by Aaron-Sterling** [comment]
Closed due to lack of activity.
